"""add certificates table

Revision ID: a705b8d5d275
Revises: 7d5bb39b0e83
Create Date: 2026-07-16 13:19:10.903491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a705b8d5d275'
down_revision: Union[str, None] = '7d5bb39b0e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verification_code', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(length=100), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=True),
    sa.Column('course_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('course_track_snapshot', sa.String(length=100), nullable=False),
    sa.Column('difficulty_snapshot', sa.String(length=50), nullable=False),
    sa.Column('student_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('issued_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_certificate_user_course')
    )
    op.create_index(op.f('ix_certificates_user_id'), 'certificates', ['user_id'], unique=False)
    op.create_index(op.f('ix_certificates_verification_code'), 'certificates', ['verification_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certificates_verification_code'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_user_id'), table_name='certificates')
    op.drop_table('certificates')
    # ### end Alembic commands ###
