"""add course_unlocks table

Revision ID: aed0a1931b3f
Revises: d9bee7dff77f
Create Date: 2026-07-23 15:55:08.245791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aed0a1931b3f'
down_revision: Union[str, None] = 'd9bee7dff77f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_unlocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(length=100), nullable=False),
    sa.Column('granted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('granted_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['granted_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_course_unlock_user_course')
    )
    op.create_index(op.f('ix_course_unlocks_course_id'), 'course_unlocks', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_unlocks_user_id'), 'course_unlocks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_unlocks_user_id'), table_name='course_unlocks')
    op.drop_index(op.f('ix_course_unlocks_course_id'), table_name='course_unlocks')
    op.drop_table('course_unlocks')
    # ### end Alembic commands ###
