"""add student profile fields and plan_expires_at to users

Revision ID: cb3f207d62d2
Revises: 92e4a99a209a
Create Date: 2026-07-16 12:56:12.112356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3f207d62d2'
down_revision: Union[str, None] = '92e4a99a209a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Postgres enum types must exist before a column can reference them —
    # op.add_column() alone does not emit CREATE TYPE.
    sa.Enum('male', 'female', 'non_binary', 'prefer_not_to_say', name='gender').create(op.get_bind(), checkfirst=True)
    sa.Enum('african', 'coloured', 'indian', 'white', 'other', 'prefer_not_to_say', name='racecategory').create(op.get_bind(), checkfirst=True)

    op.add_column('users', sa.Column('plan_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.Enum('male', 'female', 'non_binary', 'prefer_not_to_say', name='gender', create_type=False), nullable=True))
    op.add_column('users', sa.Column('job_title', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('nationality', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('race', sa.Enum('african', 'coloured', 'indian', 'white', 'other', 'prefer_not_to_say', name='racecategory', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'race')
    op.drop_column('users', 'nationality')
    op.drop_column('users', 'job_title')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'plan_expires_at')
    # ### end Alembic commands ###
    sa.Enum(name='racecategory').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='gender').drop(op.get_bind(), checkfirst=True)
