"""add python_promo_granted to users

Revision ID: d9bee7dff77f
Revises: a705b8d5d275
Create Date: 2026-07-23 14:46:56.692865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9bee7dff77f'
down_revision: Union[str, None] = 'a705b8d5d275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('python_promo_granted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'python_promo_granted')
    # ### end Alembic commands ###
