"""add expiry to course unlocks

Revision ID: f2b60cf12b0e
Revises: aed0a1931b3f
Create Date: 2026-07-23 16:00:41.293807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2b60cf12b0e'
down_revision: Union[str, None] = 'aed0a1931b3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_unlocks', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('courses', sa.Column('globally_unlocked_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'globally_unlocked_until')
    op.drop_column('course_unlocks', 'expires_at')
    # ### end Alembic commands ###
