# TODO 1: pick a small base image (hint: python:3.12-slim)
FROM ___

# TODO 2: set the working directory inside the container
WORKDIR ___

# TODO 3: copy app.py from this folder into the working directory
COPY ___ ___

# TODO 4: set the command that runs when the container starts
CMD ["python", "___"]
